aws:
  region: eu-north-1
  bucket_name: catalog-learning-project
  role_arn: arn:aws:iam::980805786648:role/GlueFullAccessRole

glue:
  landing_db: landing_db
  fdp_db: fdp_db
  table_prefix: landing_sys01_2026     # KEEP THIS
  glue_version: "3.0"
  temp_dir: "s3://catalog-learning-project/temp/"

s3_paths:
  source_prefix: source_zone/
  target_prefix: fdp_zone/
  script_prefix: scripts/
  temp_prefix: temp/

logging:
  level: INFO
  retention_days: 7
